### ISSUE TITLE
Unexpected error running script

### ISSUE THREAD

**Issue by cincykid67** [mdnghtman/us122-linux#1]
First, thank you for writing the script and making it available.  It is a potential time-saver.

I am trying to use the Tascam US-122 on a system running Bodhi Linux 5.0 Legacy, which is a 32-bit derivative of Ubuntu 18.04.  I ran your script and the installation started correctly, but it stopped when I received this error:

tascam-us_122.sh: 30: tascam-us_122.sh: Syntax error: "(" unexpected

I wanted to pass this along in case anyone else is trying to use the script.

Vielen Dank

**Comment by mdnghtman** [comment]
Thank you for opening this issue. 
I'll try to reproduce this as soon as possible, and update the script accordingly, as it is rather outdated in its current form. I also want to add some udev-rules as documented in this archlinux-wiki article: https://wiki.archlinux.org/index.php/Professional_audio#Tascam_US-122

**Comment by mdnghtman** [comment]
Alright, i reran the script on 64-bit Xubuntu and 32-bit Ubuntu Studio and couldn't reproduce the error.
I speculate that the Tascam hasn't been properly detected and therefor did not show in lsusb. But that's just a speculation. Hope you did manage to get the Tascam running anyway.
